import React from 'react';
import Head from 'next/head';
import HeadPage from '@/components/HeadPage/HeadPage';
import LayoutSection from '@/components/Section/LayoutSection';

const QuieroArrendar = () => {
  return (
    <LayoutSection>
      <Head>
        <title>Quiero Arrendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1
        style={{
          backgroundColor: 'red',
          height: '500px',
          width: '100%',
          marginTop: '100px',
        }}
      >
        Quiero Arrendar
      </h1>
    </LayoutSection>
  );
};

export default QuieroArrendar;
